### ISSUE TITLE
Little more help please.

### ISSUE THREAD

**Issue by SathvikKS** [nitinjs/india-sms-api#2]
I run a WordPress site on Linux. So I wanted to know how I can install it in Linux. A detailed tutorial would be helpful. I don't know c, I am not asking you to teach me that, but just enough for me o get it working in Linux VPS (ubuntu 18.04)

**Comment by nitinjs** [comment]
.net core builds of this library are planned.

to get it working in Linux:
you have to use .net core and setup a web-service on server.

1. build this library using .net core
2. set-up web-service consuming the library
3. hit the web service from php/wordpress

**Comment by SathvikKS** [comment]
Please, I'm sorry but I did not understand.

**Comment by nitinjs** [comment]
currently you cannot use this with php/wordpress

**Comment by SathvikKS** [comment]
Forget WordPress. Only php?

**Comment by SathvikKS** [comment]
I have installed dot net core in my ubuntu as per tutorial is given here. https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/runtime-current

**Comment by nitinjs** [comment]
I will build the library for linux (planned)

**Comment by SathvikKS** [comment]
It is a bit urgent, so is there anyways how you can explain your second post in detail?

**Comment by nitinjs** [comment]
well, in that case you can quickly host the web-service on windows azure
and then execute it from your php 
https://www.codeproject.com/Articles/1368337/Implementing-SMS-API-using-Azure-Serverless-Functi

**Comment by SathvikKS** [comment]
windows azure? I use google cloud platform and aws, both on free tier.

**Comment by SathvikKS** [comment]
Well, it seems like you currently cannot help me with this. You build a new script for Linux, based on PHP should resolve. Anyways I will be eagerly waiting for it, cause I get a lot of users using disposable emails, and this will be the only fix. Thank You.
